
---
- name: Playbook principal
  hosts: test

  vars_files:
    - secrets.yml
  vars_prompt:
    - name: ncupdate
      prompt: ¿Quieres actualizar el cliente Nextcloud_Linux al final de la configuración? (s/N)
      private: false
      default: "no"

  handlers:
    - name: restart cron
      become: true
      systemd:
        name: cron
        state: restarted
    - name: restart ntp
      become: true
      systemd:
        name: systemd-timesyncd
        state: restarted
    - name: reboot
      become: true
      reboot:

  tasks:
#  - import_tasks: tasks/time_locales.yml
   - import_tasks: tasks/paquetes.yml
   - import_tasks: tasks/users_config.yml
   - import_tasks: tasks/nextcloud.yml

# otras bondades de bash_custom (paths y docker compose completion)
# exclude dirs de Nextcloud sync (ver ayuda del comando)
