---
# En el host a configurar necesitamos que sudo esté instalado y que el usuario pertenezca
#   al grupo sudo. Tambien necesitamos copiar al servidor las claves publicas ssh de ansible.
#
# En el ordenador control necesitamos el paquete whois y python3-passlib.

- name: Playbook principal
  hosts: servers

  vars_files:
    - vars/vars.yml
    - vars/vault.yml

  handlers:    # restart cron, restart ntp, restart ssh, reboot
    - import_tasks: handlers/handlers.yml

  tasks:
#    - import_tasks: tasks/time_locales.yml
#    - import_tasks: tasks/paquetes.yml
#    - import_tasks: tasks/users_config.yml
#    - import_tasks: tasks/push_ssh_public_keys.yml
#    - import_tasks: tasks/nextcloud_basic_client.yml
#    - import_tasks: tasks/docker.yml
#    - import_tasks: tasks/samba_client.yml



# otras bondades de bash_custom (paths y docker compose completion)
# Samba server
