---
- name: Copia .sudo_plugin a las carpetas home de los usuarios
  become: true
  copy:
    src: files/sudo_plugin
    dest: "{{ item.destino }}/.sudo_plugin"
    owner: "{{ item.usuario }}"
    group: "{{ item.usuario }}"
    mode: 0600

- name: A単ade .sudo_plugin en .bashrc de cada usuario
  become: true
  blockinfile:
    path: "{{ item.destino }}/.bashrc"
    # prepend_newline: true    No funciona en esta version de ansible
    block: |
      if [ -f ~/.sudo_plugin ]; then
        source ~/.sudo_plugin
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK: A単ade .sudo_plugin"

- name: Copia .bash_aliases a las carpetas home de los usuarios
  become: true
  copy:
    src: files/bash_aliases
    dest: "{{ item.destino }}/.bash_aliases"
    owner: "{{ item.usuario }}"
    group: "{{ item.usuario }}"
    mode: 0600

- name: A単ade .bash_aliases en .bashrc de cada usuario
  become: true
  blockinfile:
    path: "{{ item.destino }}/.bashrc"
    # prepend_newline: true    No funciona en esta version de ansible
    block: |
      if [ -f ~/.bash_aliases ]; then
        source ~/.bash_aliases
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK: A単ade .bash_aliases"

- name: Exports EDITOR=nano para los usuarios de este play
  become: true
  blockinfile:
    path: "{{ item.destino }}/.bashrc"
    # prepend_newline: true    No funciona en esta version de ansible
    block: |
      export EDITOR=/usr/bin/nano
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Editor por defecto nano"

- name: Crea directorio bin/ en la carpeta de los usuarios.
  become: true
  file:
    path: "{{ item.destino }}/bin"
    owner: "{{ item.usuario }}"
    group: "{{ item.usuario }}"
    state: directory

