---
- name: Se asegura de que no existan los siguientes paquetes.
  become: true
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Add Docker's official GPG key.
  become: true
  apt:
    name:
      - ca-certificates
      - curl
    cache_valid_time: 3600
    update_cache: true

- name: Crea el directorio /etc/apt/keyrings con permisos 0755.
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '755'

- name: Descarga las gpg-keys.
  become: true
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Genera el texto para incluir en /etc/apt/sources.list.d/docker.list posteriormente.
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable"
  args:
    executable: /usr/bin/bash
  register: texto
  changed_when: false

- name: Comprueba si existe /etc/apt/sources.list.d/docker.list
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: stat_docker_list

- name: Crea /etc/apt/sources.list.d/docker.list si no existe
  become: true
  when: stat_docker_list['stat']['exists'] == false
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: touch
    mode: '644'
    owner: root
    group: root

- name: Añade el texto del repositorio al fichero /etc/apt/sources.list.d/docker.list
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "{{ texto['stdout'] }}"
    state: present

- name: Actualiza la cache apt e instala paquetes docker.
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Añade a {{ default_user }} al grupo docker.
  become: true
  user:
    name: "{{ default_user }}"
    groups: docker
    append: true
