---
- name: Actualiza cache e instala nextcloud-desktop.
  become: true
  apt:
    name:
      - nextcloud-desktop
    update_cache: true
    cache_valid_time: 3600

- name: Instala y configura el cliente Nextcloud
  shell: >
    nextcloud
    --userid {{ ncuser }}
    --apppassword {{ ncpassword }}
    --overrideserverurl {{ ncfqdn }}
    &
  args:
    creates: "/home/{{ default_user }}/.config/Nextcloud/nextcloud.cfg"
