---
- name: Instala nextcloud-desktop-cmd
  become: true
  apt:
    name:
      - nextcloud-desktop-cmd
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Crea carpeta Nextcloud_basic_client
  become: true
  file:
    path: "/home/{{ default_user }}/Nextcloud_basic_client"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

- name: Copia .ncsync a /home/{{ default_user }}
  become: true
  template:
    src: templates/ncsync.j2
    dest: "/home/{{ default_user }}/.ncsync"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: 0600

- name: Añade .ncsync en el .bashrc de {{ default_user }}
  become: true
  blockinfile:
    path: "/home/{{ default_user }}/.bashrc"
    # prepend_newline: true    No funciona en esta version de ansible
    block: |
      if [ -f ~/.ncsync ]; then
        source ~/.ncsync
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Añade .ncsync"

- name: Crea directorios bin/ y log/ en  /home/{{ default_user }}/
  become: true
  file:
    path: "/home/{{ default_user }}/{{ item }}"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    state: directory
  loop:
    - bin
    - log

- name: Copia nextcloud_linux_update.sh a /home/{{ default_user }}/bin
  become: true
  template:
    src: templates/nextcloud_linux_update.sh.j2
    dest: "/home/{{ default_user }}/bin/nextcloud_linux_update.sh"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: 0700

- name: Añade orden para actualizar Nextcloud Linux a diario a las 7 AM
  become: true
  cron:
    name: Nextcloud_basic_client update
    user: "{{ default_user }}"
    hour: 7
    job: "/home/{{ default_user }}/bin/nextcloud_linux_update.sh"

- name: Copia el script notas a /usr/local/bin
  become: true
  copy:
    src: notas
    dest: /usr/local/bin
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: 0755

- name: Stats Notas.txt para luego actualizar Nextcloud o no.
  stat:
    path: "/home/{{ default_user }}/Nextcloud_basic_client/Notas/Notas.txt"
  register: stat_notas

- name: Actualiza el cliente Nextcloud_basic_client, necesario para el comando notas.
  become: true
  when: stat_notas.stat.exists == false
  command: "/home/{{ default_user }}/bin/nextcloud_linux_update.sh"
  no_log: true
